---@diagnostic disable: duplicate-set-field
-- Grab local references to global variables. We are trading RAM to decrease CPU usage and hopefully increase FPS
local GetAreaInfo = C_Map.GetAreaInfo
local LibStub = LibStub
local UnitClassBase = UnitClassBase
local UnitFactionGroup = UnitFactionGroup

------------------- Get addon reference --------------------
---@class RepByZone: AceAddon, AceEvent-3.0, AceConsole-3.0
local RepByZone = LibStub("AceAddon-3.0"):GetAddon("RepByZone")
local playerClass = UnitClassBase("player")

local subZonesAndFactions
function RepByZone:SubZonesAndFactionsList()
	if subZonesAndFactions then return subZonesAndFactions end
	local H = UnitFactionGroup("player") == "Horde"
	local A = UnitFactionGroup("player") == "Alliance"
	subZonesAndFactions = {
		-- [GetAreaInfo(areaID)]  = factionID
		-- see https://wago.tools/db2/AreaTable?build=3.80.1.66991

		[GetAreaInfo(35)]		= 21,						-- Booty Bay/Booty Bay
		[GetAreaInfo(36)]		= A and 730 or H and 729,	-- Alterac Mountains/Stormpike Guard or Frostwolf Clan
		[GetAreaInfo(43)]		= 87,						-- Wild Shore/Bloodsail Buccaneers
		[GetAreaInfo(100)]		= 47,						-- Nesingwary's Expedition/Ironforge
		[GetAreaInfo(133)]		= 54,						-- New Tinkertown/Gnomeregan
		[GetAreaInfo(150)]		= 72,						-- Menethil Harbor/Stormwind
		[GetAreaInfo(152)]		= 1106,						-- The Bulwark/Argent Crusade
		[GetAreaInfo(193)]		= A and 72 or H and 68,		-- Ruins of Andorhal/Stormwind or Undercity
		[GetAreaInfo(196)]		= 72,						-- Uthor's Tomb/Stormwind
		[GetAreaInfo(197)]		= 72,						-- Sorrow Hill/Stormwind
		[GetAreaInfo(199)]		= 72,						-- Felstone Field/Stormwind
		[GetAreaInfo(201)]		= 68,						-- Gahrron's Withering/Undercity
		[GetAreaInfo(202)]		= 68,						-- Writhing Haunt/Undercity
		[GetAreaInfo(250)]		= 59,						-- Ruins of Thaurissan/Thorium Brotherhood
		[GetAreaInfo(279)]		= 1090,						-- Dalaran Crater/Kirin Tor
		[GetAreaInfo(280)]		= 349,						-- Strahnbrad/Ravenholdt
		[GetAreaInfo(288)]		= 72,						-- Azurelode Mine/Stormwind
		[GetAreaInfo(297)]		= 81,						-- Jaguero Isle/Thunder Bluff
		[GetAreaInfo(299)]		= 72,						-- Menethil Bay/Stormwind
		[GetAreaInfo(313)]		= 349,						-- Northfold Manor/Ravenholdt
		[GetAreaInfo(315)]		= 72,						-- Dabyrie's Farmstead/Stormwind
		[GetAreaInfo(317)]		= A and 471 or H and 530,	-- Witherbark Village/Wildhammer Clan or Darkspear Trolls
		[GetAreaInfo(320)]		= 72,						-- Refuge Pointe/Stormwind
		[GetAreaInfo(321)]		= 68,						-- Hammerfall/Undercity
		[GetAreaInfo(324)]		= 349,						-- Stromgarde Keep/Ravenholdt
		[GetAreaInfo(327)]		= 21,						-- Faldir's Cove/Booty Bay
		[GetAreaInfo(328)]		= 21,						-- The Drowned Reef/Booty Bay
		[GetAreaInfo(330)]		= 47,						-- Thandol Span/Ironforge
		[GetAreaInfo(350)]		= 69,						-- Quel'Danil Lodge/Darnassus
		[GetAreaInfo(359)]		= A and 47 or H and 81,		-- Bael Modan/Ironforge or Thunder Bluff
		[GetAreaInfo(367)]		= 530,						-- Sen'jen Village/Darkspear Trolls
		[GetAreaInfo(368)]		= 530,						-- Echo Isles/Darkspear Trolls
		[GetAreaInfo(385)]		= 72,						-- Northwatch Hold/Stormwind
		[GetAreaInfo(392)]		= 470,						-- Ratchet/Ratchet
		[GetAreaInfo(393)]		= 530,						-- Darkspear Strand/Darkspear Trolls
		[GetAreaInfo(439)]		= A and 54 or H and 76,		-- The Shimmering Flats/Gnomeregan or Orgrimmar
		[GetAreaInfo(484)]		= A and 69 or H and 81,		-- Freewind Post/Darnassus or Thunder Bluff
		[GetAreaInfo(501)]		= 369,						-- Beezil's Wreck/Gadgetzan
		[GetAreaInfo(517)]		= 1358,						-- Tidefury Cove/Nat Pagle
		[GetAreaInfo(596)]		= 470,						-- Kodo Graveyard/Ratchet
		[GetAreaInfo(603)]		= 69,						-- Sargeron/Darnassus
		[GetAreaInfo(604)]		= 93,						-- Magram Village (Shok'Thokar)/Magram Clan Centaur
		[GetAreaInfo(606)]		= 92,						-- Gelkis Village/Gelkis Clan Centaur
		[GetAreaInfo(608)]		= 69,						-- Nijel's Point/Darnassus
		[GetAreaInfo(609)]		= 93,						-- Kolkar Village/Magram Clan Centaur
		[GetAreaInfo(657)]		= 930,						-- The Harborage/Exodar
		[GetAreaInfo(702)]		= 69,						-- Rut'theran Village/Darnassus
		[GetAreaInfo(721)]		= 54,						-- Gnomeregan/Gnomeregan
		[GetAreaInfo(813)]		= 1106,						-- The Bulwark/Argent Crusade
		[GetAreaInfo(880)]		= 471,						-- Thandol Span (Arathi Highlands)/Wildhammer Clan
		[GetAreaInfo(881)]		= 47,						-- Thandol Span (Wetlands)/Ironforge
		[GetAreaInfo(896)]		= A and 730 or H and 729,	-- Purgation Isle/Stormpike Guard or Frostwolf Clan
		[GetAreaInfo(978)]		= A and 471 or H and 530,	-- Zul'Farrak/Wildhammer Clan or Darkspear Trolls
		[GetAreaInfo(1016)]		= 69,						-- Direforge Hill/Darnassus
		[GetAreaInfo(1025)]		= 69,						-- The Green Belt/Darnassus
		[GetAreaInfo(1057)]		= A and 47 or H and 68,		-- Thoradin's Wall (Hillsbrad Foothills)/Ironforge or Undercity
		[GetAreaInfo(1216)]		= 579,						-- Timbermaw Hold/Timbermaw Hold
		[GetAreaInfo(1220)]		= 69,						-- Darnassian Base Camp/Darnassus
		[GetAreaInfo(1446)]		= 59,						-- Thorium Point/Thorium Brotherhood
		[GetAreaInfo(1658)]		= 609,						-- Cenarion Enclave/Cenarion Circle
		[GetAreaInfo(1677)]		= A and 730 or H and 729,	-- Gavin's Naze/Stormpike Guard or Frostwolf Clan
		[GetAreaInfo(1678)]		= 72,						-- Sofera's Naze/Stormwind
		[GetAreaInfo(1679)]		= A and 730 or H and 729,	-- Corrahn's Dagger/Stormpike Guard or Frostwolf Clan
		[GetAreaInfo(1680)]		= A and 730 or H and 729,	-- The Headland/Stormpike Guard or Frostwolf Clan
		[GetAreaInfo(1741)]		= 87,						-- Gurubashi Arena/Bloodsail Buccaneers
		[GetAreaInfo(1757)]		= 87,						-- The Crimson Veil/Bloodsail Buccaneers
		[GetAreaInfo(1758)]		= 87,						-- The Riptide/Bloodsail Buccaneers
		[GetAreaInfo(1759)]		= 87,						-- The Damsel's Luck/Bloodsail Buccaneers
		[GetAreaInfo(1761)]		= 579,						-- Deadwood Village/Timbermaw Hold
		[GetAreaInfo(1762)]		= 579,						-- Felpaw Village/Timbermaw Hold
		[GetAreaInfo(1769)]		= 579,						-- Timbermaw Hold/Timbermaw Hold
		[GetAreaInfo(1778)]		= 369,						-- Sorrowmurk/Gadgetzan
		[GetAreaInfo(1837)]		= A and 471 or H and 530,	-- Witherbark Caverns/Wildhammer Clan or Darkspear Trolls
		[GetAreaInfo(1857)]		= A and 47 or H and 68,		-- Thoradin's Wall (Arathi Highlands)/Ironforge or Undercity
		[GetAreaInfo(1858)]		= 471,						-- Boulder'gor/Wildhammer Clan
		[GetAreaInfo(1941)]		= 989,						-- Caverns of Time/Keepers of Time
		[GetAreaInfo(2079)]		= A and 54 or H and 68,		-- Alcaz Island/Gnomeregan or Undercity
		[GetAreaInfo(2097)]		= A and 69 or H and 81,		-- Darkcloud Pinnacle/Darnassus or Thunder Bluff
		[GetAreaInfo(2157)]		= A and 47 or H and 81,		-- Bael'dun Keep/Ironforge or Thunder Bluff
		[GetAreaInfo(2177)]		= 87,						-- Battle Ring/Bloodsail Buccaneers
		[GetAreaInfo(2240)]		= 369,						-- Mirage Raceway/Gadgetzan
		[GetAreaInfo(2241)]		= 589,						-- Frostsaber Rock/Wintersaber Trainers
		[GetAreaInfo(2242)]		= 69,						-- The Hidden Grove/Darnassus
		[GetAreaInfo(2243)]		= 579,						-- Timbermaw Post/Timbermaw Hold
		[GetAreaInfo(2244)]		= 579,						-- Winterfall Village/Timbermaw Hold
		[GetAreaInfo(2246)]		= 579,						-- Frostfire Hot Springs/Timbermaw Hold
		[GetAreaInfo(2248)]		= 47,						-- Dun Mandarr/Ironforge
		[GetAreaInfo(2253)]		= 69,						-- Starfall Village/Darnassus
		[GetAreaInfo(2257)]		= 72,						-- Deeprun Tram/Stormwind
		[GetAreaInfo(2276)]		= 69,						-- Quel'Lithien Lodge/Darnassus
		[GetAreaInfo(2300)]		= 989,						-- Caverns of Time/Keepers of Time
		[GetAreaInfo(2379)]		= 72,						-- Azurelode Mine/Stormwind
		[GetAreaInfo(2404)]		= 69,						-- Tethris Aran/Darnassus
		[GetAreaInfo(2406)]		= 69,						-- Ranazjar Isle/Darnassus
		[GetAreaInfo(2407)]		= 470,						-- Kormek's Hut/Ratchet
		[GetAreaInfo(2408)]		= 530,						-- Shadowprey Village/Darkspear Trolls
		[GetAreaInfo(2539)]		= 530,						-- Malaka'jin/Darkspear Trolls
		[GetAreaInfo(2597)]		= A and 730 or H and 729,	-- Alterac Valley/Stormpike Guard or Frostwolf Clan
		[GetAreaInfo(2617)]		= 470,						-- Scrabblescrew's Camp/Ratchet
		[GetAreaInfo(2738)]		= 69,						-- Southwind Village/Darnassus
		[GetAreaInfo(2839)]		= A and 730 or H and 729,	-- Alterac Valley/Stormpike Guard or Frostwolf Clan
		[GetAreaInfo(2897)]		= 530,						-- Zoram'gar Outpost/Darkspear Trolls
		[GetAreaInfo(3137)]		= 69,						-- Talrendis Point/Darnassus
		[GetAreaInfo(3197)]		= 72,						-- Chillwind Camp/Stormwind
		[GetAreaInfo(3319)]		= 890,						-- Silverwing Grove/Silverwing Sentinels
		[GetAreaInfo(3426)]		= 69,						-- Staghelm Point/Darnassus
		[GetAreaInfo(3427)]		= 47,						-- Bronzebeard Encampment/Ironforge
		[GetAreaInfo(3486)]		= 349,						-- Ravenholdt Manor/Ravenholdt
		[GetAreaInfo(4010)]		= 369,						-- Mudsprocket/Gadgetzan

		--------- TBC ---------
		[GetAreaInfo(3482)]		= 922,						-- The Dead Scar (Eversong Woods)/Tranquillien
		[GetAreaInfo(3514)]		= 922,						-- The Dead Scar (Ghostlands)/Tranquillien
		[GetAreaInfo(3530)]		= A and 930 or H and 911,	-- Shadow Ridge/Exodar or Silvermoon City
		[GetAreaInfo(3547)]		= 1077,						-- Throne of Kil'jaeden/Shattered Sun Offensive
		[GetAreaInfo(3552)]		= 978,						-- Temple of Telhamat/Kurenai
		[GetAreaInfo(3554)]		= 911,						-- Falcon Watch/Silvermoon City
		[GetAreaInfo(3555)]		= 941,						-- Mag'har Post/The Mag'har
		[GetAreaInfo(3569)]		= 69,						-- Tides' Hollow/Darnassus
		[GetAreaInfo(3573)]		= 72,						-- Odesyus' Landing/Stormwind
		[GetAreaInfo(3590)]		= 69,						-- Wrathscale Lair/Darnassus
		[GetAreaInfo(3591)]		= 69,						-- Ruins of Loreth'Aran/Darnassus
		[GetAreaInfo(3598)]		= 69,						-- Wyrmscar Island/Darnassus
		[GetAreaInfo(3623)]		= 933,						-- Aeris Landing/The Consortium
		[GetAreaInfo(3673)]		= 47,						-- Nesingwary Safari/Ironforge
		[GetAreaInfo(3628)]		= A and 930 or H and 911,	-- Halaa/Exodar or Silvermoon City
		[GetAreaInfo(3630)]		= 933,						-- Oshu'gun/The Consortium
		[GetAreaInfo(3631)]		= 933,						-- Spirit Fields/The Consortium
		[GetAreaInfo(3644)]		= 930,						-- Telredor/Exodar
		[GetAreaInfo(3645)]		= 530,						-- Zabra'jin/Darkspear Trolls
		[GetAreaInfo(3646)]		= 970,						-- Quagg Ridge/Sporeggar
		[GetAreaInfo(3647)]		= 970,						-- The Spawning Glen/Sporeggar
		[GetAreaInfo(3649)]		= 970,						-- Sporeggar/Sporeggar
		[GetAreaInfo(3652)]		= 970,						-- Funggor Cavern/Sporeggar
		[GetAreaInfo(3674)]		= 942,						-- Cenarion Thicket/Cenarion Expedition
		[GetAreaInfo(3679)]		= 1031,						-- Skettis/Sha'tari Skyguard
		[GetAreaInfo(3680)]		= 1031,						-- Blackwind Valley/Sha'tari Skyguard
		[GetAreaInfo(3681)]		= 934,						-- Firewing Point/The Scryers
		[GetAreaInfo(3683)]		= 941,						-- Stonebreaker Hold/The Mag'har
		[GetAreaInfo(3684)]		= 69,						-- Allerian Stronghold/Darnassus
		[GetAreaInfo(3690)]		= 1031,						-- Blackwind Lake/Sha'tari Skyguard
		[GetAreaInfo(3691)]		= 1031,						-- Lake Ere'Noru/Sha'tari Skyguard
		[GetAreaInfo(3718)]		= 530,						-- Swamprat Post/Darkspear Trolls
		[GetAreaInfo(3719)]		= 941,						-- Bleeding Hollow Ruins/The Mag'har
		[GetAreaInfo(3744)]		= 76,						-- Shadowmoon Village/Orgrimmar
		[GetAreaInfo(3745)]		= 471,						-- Wildhammer Stronghold/Wildhammer Clan
		[GetAreaInfo(3754)]		= 932,						-- Altar of Sha'tar/The Aldor
		[GetAreaInfo(3758)]		= 1015,						-- Netherwing Fields/Netherwing
		[GetAreaInfo(3759)]		= 1015,						-- Netherwing Ledge/Netherwing
		[GetAreaInfo(3766)]		= 978,						-- Orebor Harborage/Kurenai
		[GetAreaInfo(3778)]		= 1068,						-- Draenethyst Mine/Explorer's League
		[GetAreaInfo(3769)]		= 941,						-- Thunderlord Stronghold/The Mag'har
		[GetAreaInfo(3771)]		= 69,						-- The Living Grove/Darnassus
		[GetAreaInfo(3772)]		= 69,						-- Sylvanaar/Darnassus
		[GetAreaInfo(3784)]		= 1031,						-- Forge Camp: Terror/Sha'tari Skyguard
		[GetAreaInfo(3785)]		= 1031,						-- Forge Camp: Wrath/Sha'tari Skyguard
		[GetAreaInfo(3792)]		= 933,						-- Mana-Tombs/The Consortium
		[GetAreaInfo(3801)]		= 941,						-- Mag'har Grounds/The Mag'har
		[GetAreaInfo(3806)]		= 911,						-- Supply Caravan/Silvermoon City
		[GetAreaInfo(3808)]		= 942,						-- Cenarion Post/Cenarion Expedition
		[GetAreaInfo(3816)]		= 21,						-- Zeppelin Crash/Booty Bay
		[GetAreaInfo(3828)]		= 942,						-- Ruuan Weald/Cenarion Expedition
		[GetAreaInfo(3839)]		= 1011,						-- Abandoned Armory/Lower City
		[GetAreaInfo(3842)]		= 935,						-- Tempest Keep (Netherstorm)/The Sha'tar
		[GetAreaInfo(3864)]		= 1031,						-- Bash'ir Landing/Sha'tari Skyguard
		[GetAreaInfo(3896)]		= 932,						-- Aldor Rise/The Aldor
		[GetAreaInfo(3898)]		= 934,						-- Scryer's Tier/The Scryers
		[GetAreaInfo(3899)]		= 1011,						-- Lower City/Lower City
		[GetAreaInfo(3901)]		= 69,						-- Allerian Post/Darnassus
		[GetAreaInfo(3902)]		= 941,						-- Stonebreaker Camp/The Mag'har
		[GetAreaInfo(3918)]		= 54,						-- Toshley's Station/Gnomeregan
		[GetAreaInfo(3936)]		= 471,						-- Deathforge Tower/Wildhammer Clan
		[GetAreaInfo(3937)]		= 76,						-- Slag Watch/Orgrimmar
		[GetAreaInfo(3938)]		= 934,						-- Sanctum of the Stars/The Scryers
		[GetAreaInfo(3951)]		= 942,						-- Evergrove/Cenarion Expedition
		[GetAreaInfo(3952)]		= 942,						-- Wyrmskull Bridge/Cenarion Expedition
		[GetAreaInfo(3958)]		= 1031,						-- Sha'tari Base Camp/Sha'tari Skyguard
		[GetAreaInfo(3965)]		= 1015,						-- Netherwing Mines/Netherwing
		[GetAreaInfo(3966)]		= 1015,						-- Dragonmaw Base Camp/Netherwing
		[GetAreaInfo(3964)]		= 1031,						-- Skyguard Outpost/Sha'tari Skyguard
		[GetAreaInfo(3973)]		= 1031,						-- Blackwind Landing/Sha'tari Skyguard
		[GetAreaInfo(3974)]		= 1031,						-- Veil Harr'ik/Sha'tari Skyguard
		[GetAreaInfo(3975)]		= 1031,						-- Terokk's Rest/Sha'tari Skyguard
		[GetAreaInfo(3976)]		= 1031,						-- Veil Ala'rak/Sha'tari Skyguard
		[GetAreaInfo(3977)]		= 1031,						-- Upper Veil Shil'ak/Sha'tari Skyguard
		[GetAreaInfo(3978)]		= 1031,						-- Lower Veil Shil'ak/Sha'tari Skyguard
		[GetAreaInfo(5554)]		= 935,						-- The Mechanar Entrance/The Sha'tar
		[GetAreaInfo(5555)]		= 935,						-- The Botanica Entrance/The Sha'tar
		[GetAreaInfo(5556)]		= 935,						-- The Arcatraz Entrance/The Sha'tar

		--------- WotLK ---------
		[GetAreaInfo(3987)]		= 1073,						-- The Isle of Spears/The Kalu'ak
		[GetAreaInfo(3988)]		= 1073,						-- Kamagua/The Kalu'ak
		[GetAreaInfo(3990)]		= 1073,						-- Scalawag Point/The Kalu'ak
		[GetAreaInfo(3996)]		= 1068,						-- Baelgun's Excavation Site/Explorer's League
		[GetAreaInfo(3997)]		= 1068,						-- Explorers' League Outpost/Explorers' League
		[GetAreaInfo(3999)]		= 1068,						-- Steel Gate/Explorers' League
		[GetAreaInfo(4018)]		= 1064,						-- Camp Winterhoof/The Taunka
		[GetAreaInfo(4023)]		= 1090,						-- Amber Ledge/Kirin Tor
		[GetAreaInfo(4024)]		= 1090,						-- Coldarra/Kirin Tor
		[GetAreaInfo(4033)]		= 942,						-- Winterfin Village/Cenarion Expedition
		[GetAreaInfo(4037)]		= 1064,						-- Taunka'le Village/The Taunka
		[GetAreaInfo(4040)]		= 1073,						-- Njord's Breath Bay/The Kalu'ak
		[GetAreaInfo(4041)]		= 1073,						-- Kaskala/The Kalu'ak
		[GetAreaInfo(4097)]		= 942,						-- Winterfin Caverns/Cenarion Expedition
		[GetAreaInfo(4099)]		= 942,						-- Winterfin Retreat/Cenarion Expedition
		[GetAreaInfo(4113)]		= 1073,						-- Unu'pe/The Kalu'ak
		[GetAreaInfo(4120)]		= 1090,						-- The Nexus/Kirin Tor
		[GetAreaInfo(4121)]		= 1090,						-- Transitus Shield/Kirin Tor
		[GetAreaInfo(4151)]		= 1064,						-- Westwind Refuge Camp/The Taunka
		[GetAreaInfo(4152)]		= 1073,						-- Moa'ki Harbor/The Kalu'ak
		[GetAreaInfo(4155)]		= 1073,						-- The Half Shell/The Kalu'ak
		[GetAreaInfo(4158)]		= 1037,						-- Stars' Rest/Alliance Vanguard
		[GetAreaInfo(4165)]		= 1052,						-- Agmar's Hammer/Horde Expedition
		[GetAreaInfo(4169)]		= 1037,						-- Fordragon Hold/Alliance Vanguard
		[GetAreaInfo(4170)]		= 1052,						-- Kor'kron Vanguard/Horde Expedition
		[GetAreaInfo(4171)]		= A and 1037 or H and 1052,	-- The Court of Skulls/Alliance Vanguard or Horde Expedition
		[GetAreaInfo(4172)]		= A and 1037 or H and 1052,	-- Angrathar the Wrathgate/Alliance Vanguard or Horde Expedition
		[GetAreaInfo(4177)]		= 1037,						-- Wintergarde Keep/Alliance Vanguard
		[GetAreaInfo(4178)]		= 1037,						-- Wintergarde Mine/Alliance Vanguarde
		[GetAreaInfo(4186)]		= 1067,						-- Venomspite/The Hand of Vengeance
		[GetAreaInfo(4188)]		= 1037,						-- The Carrion Fields/Alliance Vanguard
		[GetAreaInfo(4189)]		= 942,						-- D.E.H.T.A Encampment/Cenarion Expedition
		[GetAreaInfo(4190)]		= 1037,						-- Thorson's Post/Alliance Vanguard
		[GetAreaInfo(4191)]		= 1106,						-- Light's Trust/Argent Crusade
		[GetAreaInfo(4211)]		= 1064,						-- Camp Oneqwah/The Taunka
		[GetAreaInfo(4224)]		= 1073,						-- The Briny Pinnacle/The Kalu'ak
		[GetAreaInfo(4226)]		= 1073,						-- Iskaal/The Kalu'ak
		[GetAreaInfo(4227)]		= 530,						-- Dragon's Fall/Darkspear Trolls
		[GetAreaInfo(4233)]		= 1106,						-- Dawn's Reach/Argent Crusade
		[GetAreaInfo(4234)]		= 1106,						-- Naxxramas/Argent Crusade
		[GetAreaInfo(4243)]		= 1037,						-- Wintergarde Crypt/Alliance Vanguard
		[GetAreaInfo(4246)]		= 1037,						-- Wintergarde Mausoleum/Alliance Vanguard
		[GetAreaInfo(4256)]		= A and 1094 or H and 1124,	-- Drak'mar Lake/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4261)]		= 68,						-- Ghostblade Point/Undercity
		[GetAreaInfo(4281)]		= 1098,						-- Acherus: The Ebon Hold (Eastern Kingdoms)/Knights of the Ebon Blade
		[GetAreaInfo(4284)]		= 47,						-- Nesingwary Base Camp/Ironforge
		[GetAreaInfo(4286)]		= 1105,						-- The Bones of Nozronn/The Oracles
		[GetAreaInfo(4287)]		= 1104,						-- Kartak's Hold/Frenzyheart Tribe
		[GetAreaInfo(4288)]		= 1105,						-- Sparktouched Haven/The Oracles
		[GetAreaInfo(4291)]		= 1105,						-- Rainspeaker Canopy/The Oracles
		[GetAreaInfo(4292)]		= 1104,						-- Frenzyheart Hill/Frenzyheart Tribe
		[GetAreaInfo(4297)]		= 1105,						-- Mosswalker Village/The Oracles
		[GetAreaInfo(4303)]		= 1104,						-- Hardknuckle Clearing/Frenzyheart Tribe
		[GetAreaInfo(4306)]		= 1105,						-- Mistwhisper Village/The Oracles
		[GetAreaInfo(4308)]		= 1104,						-- Spearborn Encampment/Frenzyheart Tribe
		[GetAreaInfo(4312)]		= 1098,						-- Ebon Watch/Knights of the Ebon Blade
		[GetAreaInfo(4369)]		= 47,						-- Dorian's Outpost/Ironforge
		[GetAreaInfo(4342)]		= 1098,						-- Acherus: The Ebon Hold (Death Knight start)/Knights of the Ebon Blade
		[GetAreaInfo(4392)]		= 1105,						-- The Stormwright's Shelf/The Oracles
		[GetAreaInfo(4429)]		= 1085,						-- Grom'arsh Crash-Site/Warsong Offensive
		[GetAreaInfo(4418)]		= 21,						-- K3/Booty Bay
		[GetAreaInfo(4428)]		= 1126,						-- Frosthold/The Frostborn
		[GetAreaInfo(4441)]		= 1064,						-- Camp Tunka'lo/The Taunka
		[GetAreaInfo(4442)]		= 1068,						-- Brann's Base-Camp/Explorers' League
		[GetAreaInfo(4458)]		= 21,						-- Sparksocket Minefield/Booty Bay
		[GetAreaInfo(4459)]		= 21,						-- Ricket's Folly/Booty Bay
		[GetAreaInfo(4479)]		= A and 1094 or H and 1124,	-- Winter's Breath Lake/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4485)]		= 1126,						-- The Inventor's Library/The Frostborn
		[GetAreaInfo(4487)]		= 1085,						-- Frostfloe Deep/Warsong Offensive
		[GetAreaInfo(4501)]		= 1106,						-- The Argent Vanguard/Argent Crusade
		[GetAreaInfo(4502)]		= 1126,						-- Mimir's Workshop/The Frostborn
		[GetAreaInfo(4503)]		= A and 1094 or H and 1124,	-- Ironwall Dam/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4504)]		= 1106,						-- Valley of Echoes/Argent Crusade
		[GetAreaInfo(4505)]		= 1106,						-- The Breach/Argent Crusade
		[GetAreaInfo(4506)]		= 1106,						-- Scourgeholme/Argent Crusade
		[GetAreaInfo(4507)]		= A and 1037 or H and 1052,	-- The Broken Front/Alliance Vanguard or Horde Expedition
		[GetAreaInfo(4511)]		= A and 1037 or H and 1052,	-- The Skybreaker/Alliance Vanguard or Horde Expedition
		[GetAreaInfo(4512)]		= A and 1037 or H and 1052,	-- Orgrim's Hammer/Alliance Vanguard or Horde Expedition
		[GetAreaInfo(4516)]		= 1106,						-- Ironwall Rampart/Argent Crusade
		[GetAreaInfo(4522)]		= 1156,						-- Icecrown Citadel/The Ashen Verdict
		[GetAreaInfo(4536)]		= A and 1068 or H and 1085,	-- Frosthowl Cavern/Explorers' League or Warsong Offensive
		[GetAreaInfo(4541)]		= 1106,						-- Vanguard Infirmary/Argent Crusade
		[GetAreaInfo(4558)]		= A and 1094 or H and 1124,	-- Sunreaver's Command/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4559)]		= A and 1094 or H and 1124,	-- Windrunner's Overlook/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4580)]		= 1106,						-- Crusaders' Pinnacle/Argent Crusade
		[GetAreaInfo(4593)]		= 1106,						-- The Pit of Fiends/Argent Crusade
		[GetAreaInfo(4616)]		= A and 1094 or H and 1124,	-- Sunreaver's Sanctuary/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4646)]		= A and 1094 or H and 1124,	-- Ashwood Lake/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4658)]		= 1106,						-- Argent Tournament Grounds/Argent Crusade
		[GetAreaInfo(4666)]		= A and 1094 or H and 1124,	-- Sunreaver Pavilion/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4667)]		= A and 1094 or H and 1124,	-- Silver Covenant Pavilion/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4669)]		= 1106,						-- The Ring of Champions/Argent Crusade
		[GetAreaInfo(4670)]		= 1106,						-- The Aspirants' Ring/Argent Crusade
		[GetAreaInfo(4671)]		= 1106,						-- The Argent Valiants' Ring/Argent Crusade
		[GetAreaInfo(4672)]		= A and 1094 or H and 1124,	-- The Alliance Valiants' Ring/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4673)]		= A and 1094 or H and 1124,	-- The Horde Valiants' Ring/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4674)]		= 1106,						-- Argent Pavilion/Argent Crusade
		[GetAreaInfo(4676)]		= A and 1094 or H and 1124,	-- Sunreaver Pavilion (Outside)/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4677)]		= A and 1094 or H and 1124,	-- Silver Covenant Pavilion (Outside)/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4740)]		= A and 1094 or H and 1124,	-- The Silver Enclave/The Silver Covenant or The Sunreavers
		[GetAreaInfo(4760)]		= A and 1094 or H and 1124,	-- The Sea Reaver's Run/The Silver Covenant or The Sunreavers
	}
	return subZonesAndFactions
end